# Generated by Django 4.2 on 2023-08-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('depto_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('dnombre', models.CharField(max_length=14)),
                ('localidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='detalleArticulo',
            fields=[
                ('detalle_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('talla', models.PositiveSmallIntegerField()),
                ('colores', models.CharField(max_length=15)),
                ('imagen1', models.CharField(max_length=150)),
                ('disponible', models.BooleanField()),
                ('composicion', models.CharField(max_length=150)),
                ('cuidados', models.CharField(max_length=150)),
                ('envio', models.CharField(max_length=100)),
                ('devolucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_disponible', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=30)),
                ('oficio', models.CharField(max_length=10)),
                ('director', models.PositiveSmallIntegerField()),
                ('fecha_alta', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('telefono', models.CharField(max_length=15)),
                ('depto_no', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='ventasApp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('imagen1', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle_no', models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='ventasApp.detallearticulo')),
            ],
        ),
    ]
